### ISSUE TITLE
ST-Storage Simultaneous Injection & Withdrawal

### ISSUE THREAD

**Issue by ThanosGkou** [AntaresSimulatorTeam/Antares_Simulator#2079]
The case of **simultaneous injection and withdrawal of st-storage** objects (of type "Battery") was observed in a real-life case study. As such, I can't really provide a directly reproducible study, but I can provide some hints that I think are relevant. The below comments are what  suspect is happening, but haven't verified it in practice.

I'm using Antares 8.6.6 in Windows 10.

When the phenomenon of simultaneous charge+discharge takes place, it wasn't in my case accompanied by spilled energy. BUT, the marginal price was a bit negative, e.g. -0.08 e/MWh, which means that the system is marginally not spilling energy, because the Cost of Spilled energy was set in my case to 0.1e/MWh. 

So, if a 1000 MW battery has 90% efficiency, a simultaneous charge+discharge would provide "free" dissipation of 100MW. These 100MW, if they were to be spilled, they would be charged at a cost of 0.1e/MWh. So, from an optimization point of view it makes sense to take advantage of this efffect, but in my opinion there should be a constraint to forbid this behaviour.

**Comment by matbossSG** [comment]
Hi,

I am not associated with RTE nor with the development of Antares so I can not answer from the implementation side.

Non-simultaneous charging and discharging constraints are non-linear because you have a multiplication of two variables:

$$P_{charge} \cdot P_{discharge} = 0$$

hence it will not fit into the current linear problem used in Antares.
You can however write the constraint as MILP using big-M reformulation, which could then be solved with a MILP solver. There's a trade-off between the solve time (number of added binary variables) and accuaracy. Since the situation where the battery volontary spills energy is only happens with positive Cost of Spilled energy or negative prices, it seems that the problem is not that recurrent at the moment (if I'm not mistaken, renewable cost cannot yet be negative in Antares). Might be interesting to follow-up in the future as the share of renewable in the system increases.

Hope it helps !

**Comment by NeutrinoZeng** [comment]
This phenomenon also occured in my study.
If too much spilled energy exists and a big penalty factor applied, a deep negative prices will occur.
The pump-storage plants will pump and generate the energy at the same time.

**Comment by flomnes** [comment]
Yes this phenomenon occurs to dissipate some energy for free. It allows the optimizer to avoid spillage costs, so in many cases it is in fact optimal to charge and discharge simultaneously.

As suggested by @matbossSG, if we introduced a binary variable per hour (charge OR discharge), I highly suspect that we would see charge/discharge/charge/discharge/etc. cycles in situations where spillage would normally occur.

**Comment by payetvin** [comment]
Should be documented

**Comment by AsiminaF** [comment]
Hi,

Could you please share where this issue was addressed? I've checked the commits and documentation but couldn't find the fix. Was it resolved in a different way, or am I looking in the wrong place?

Thanks!

**Comment by flomnes** [comment]
We closed the ticket as "won't do", but it could indeed be done with "mutual exclusion" constraints
```math
C_t \leq y_t \bar{C}
```
and
```math
D_t \leq (1-y_t) \bar{D}
```

where C_t is the rate of charge, D_t rate of discharge, y_t in [0, 1] a binary variable representing the choice for each time step.

This could be done in the modeler, what do you think @tbittar ?

**Comment by AsiminaF** [comment]
Hi,

Thank you for the detailed response.

Just to clarify for my use case: I'm using the Antares solver through the Antares Web interface for legacy studies (not hybrid), and my post-processing depends on these outputs. Given that this approach would require modeler-level changes, is there any way to work around this issue in my current setup, or should I consider the current behavior acceptable?

Thanks again for your help!

**Comment by flomnes** [comment]
@AsiminaF It would be possible to create a model with mutual exclusions with the binary variable as listed above. For example of hybrid studies, see https://github.com/AntaresSimulatorTeam/Antares_Simulator_Tests_NR/releases/download/v9.3.2c/hybrid.zip

A model for the existing short-term storage can be found here https://github.com/AntaresSimulatorTeam/Antares_Simulator_Tests_NR/blob/e8e874d4d08fe37c0ef92306f8602ffc157320d2/hybrid/8_3/input/model-libraries/antares_historic_hybrid.yml#L188-L247

**Comment by flomnes** [comment]
OK so I gave the original model to an LLM and told it to add mutual exclusions on injection & withdrawal. Here is the result
```yaml
- id: short-term-storage
  parameters:
    # … (all existing parameters stay unchanged)
    # No new parameters are required – the binary variable is a pure decision variable
  variables:
    - id: p_injection
      lower-bound: 0
      # Keep the original time‑dependent upper bound – we will tighten it with the binary
      upper-bound: p_max_injection_modulation * injection_nominal_capacity
      variable-type: continuous

    - id: p_withdrawal
      lower-bound: 0
      # Keep the original upper bound – tightened by the binary
      upper-bound: p_max_withdrawal_modulation * withdrawal_nominal_capacity
      variable-type: continuous

    - id: level
      lower-bound: lower_rule_curve * reservoir_capacity
      upper-bound: upper_rule_curve * reservoir_capacity
      variable-type: continuous

    # ---------------------------------------------------------------
    # NEW VARIABLE  --------------------------------------------------
    # ---------------------------------------------------------------
    - id: injection_active
      # A binary flag that is 1 when injection is allowed, 0 otherwise.
      variable-type: binary
      # No bounds needed – binary type already implies 0/1

  ports:
    - id: injection_port
      type: flow

  port-field-definitions:
    - port: injection_port
      field: flow
      definition: p_withdrawal - p_injection

  constraints:
    # --------------- Existing constraints ---------------------------
    - id: initial_level_constraint
      expression: level[0] = initial_level * reservoir_capacity

    - id: Level equation
      expression: level[t+1] = level + efficiency_injection * p_injection - efficiency_withdrawal * p_withdrawal + inflows

    # ---------------------------------------------------------------
    # NEW MUTUAL‑EXCLUSION CONSTRAINTS --------------------------------
    # ---------------------------------------------------------------
    # 1) Injection is only allowed when the switch is ON
    - id: injection_activation
      expression: p_injection <= injection_nominal_capacity * p_max_injection_modulation * injection_active

    # 2) Withdrawal is only allowed when the switch is OFF
    - id: withdrawal_activation
      expression: p_withdrawal <= withdrawal_nominal_capacity * p_max_withdrawal_modulation * (1 - injection_active)
```
@AsiminaF can you tell us if it works with you ? Note that you will need a MILP solver such as highs, coin, gurobi or xpress. The default sirius solver doesn't support integer variables

You can find the results in the "simulation tables", 2 large CSV files at the output's root. Not supported by antares web

**Comment by AsiminaF** [comment]
Hi everyone,

First, thank you @flomnes for your previous response and guidance on implementing the mutual exclusion constraint.

I've been trying to implement this for short-term storage as discussed in this thread, and I wanted to share my experience and ask for some follow-up guidance.

#### What I Tried
I used the hybrid example (8.3) from the Antares repository as a starting point and added the recommended formulation with binary variables:
```yaml
variables:
  - id: injection_active
    variable-type: binary
    lower-bound: 0
    upper-bound: 1

constraints:
  - id: injection_activation
    expression: p_injection <= injection_nominal_capacity * p_max_injection_modulation * injection_active
  - id: withdrawal_activation
    expression: p_withdrawal <= withdrawal_nominal_capacity * p_max_withdrawal_modulation * (1 - injection_active)
```
I also set a positive spilled energy cost to create negative prices and give the optimizer a reason to consider simultaneous injection/withdrawal as a way to avoid spillage costs.
#### The Problem
Despite trying multiple approaches, I cannot get the binary variables to behave as binaries:
1. Binary variables take fractional values (e.g., 0.55 and 0.45, summing to 1) - exactly the simultaneous injection/withdrawal I'm trying to prevent
2. I've tried both `binary` and `integer` variable types, with and without explicit bounds
3. I've tested multiple solvers that claim MIP support: `coin`  and `highs`
4. The solver logs always show: `solver [coin/highs] is used for linear problem resolution` - suggesting the problem is being relaxed to LP
5. I examined the generated MPS file and found that my binary variables appear as:
   ```
   UI BND1 x840 6
   ```
   They are marked as integer (`UI`) but with an upper bound of 6, not 1.
#### My Questions
1. Does Antares (specifically version 9.3.6) actually support user-defined binary variables in the modeler? The solver logs consistently say "linear problem resolution" even when using MIP-capable solvers.
2. Why is the upper bound being set to 6 instead of 1? I've explicitly set `upper-bound: 1` in the variable definition, but the MPS export ignores this. Is there a default upper bound being inherited from somewhere?
3. Has anyone successfully implemented this mutual exclusion constraint in practice? If so, could you share a working example?

Any insights would be greatly appreciated! I'm happy to provide my full model or MPS files if that would help diagnose the issue.

Thanks!
