### ISSUE TITLE
Github Action : test with docker for Centos CI

### ISSUE THREAD

**Issue by jmkerloch** [AntaresSimulatorTeam/Antares_Simulator#70]
For now CI is done on Ubuntu and Windows, we need to check GitHub Action with docker use so we can compile on Centos for instance.

Check this article for a simple docker use : https://www.edwardthomson.com/blog/github_actions_5_building_in_containers.html

It seems to be simple as : 

```
jobs:
  build:
    runs-on: ubuntu-latest
    container: 'centos:latest'
```
